---
name: Breaking Change PR Comment
on:
  workflow_run:
    workflows: ["Breaking Change Detection"]
    types: [completed]

jobs:
  comment:
    uses: djyasin/actions/.github/workflows/oasdiff-post-breaking-change-comment.yml@52dd49cac6d60b8dff233e7165b50f7edeff19a8
